//Productos disponibles

const productos = [
    {
        id: 1,
        nombre: "Gorra Nike",
        precio: 10800,
        cantidad: 1,
        img: "img/tienda/gorra-nike.jpg",
        descripcion: "",
    },
    {
        id: 2,
        nombre: "Gorra Adidas",
        precio: 11400,
        cantidad: 1,
        img: "img/tienda/gorra-adidas.webp",
        descripcion: "",
    },
    {
        id: 3,
        nombre: "Gorra Billabong",
        precio: 11300,
        cantidad: 1,
        img: "img/tienda/gorra-billabong.jpg",
        descripcion: "",
    },
    {
        id: 4,
        nombre: "Black Gel",
        precio: 5600,
        cantidad: 1,
        img: "img/tienda/gel.jpg",
        descripcion: "",
    },
    {
        id: 5,
        nombre: "Maquina Profesional Whal Magic Clip 5",
        precio: 52800,
        cantidad: 1,
        img: "img/tienda/whal-magic-clip.jpg",
        descripcion: "",
    },
    {
        id: 6,
        nombre: "Navaja",
        precio: 15200,
        cantidad: 1,
        img: "img/tienda/navaja.jpg",
        descripcion: "",
    },
    {
        id: 7,
        nombre: "TRESemmé",
        precio: 7100,
        cantidad: 1,
        img: "img/tienda/shampo-.webp",
        descripcion: "",
    },
    {
        id: 8,
        nombre: "Maquina Profesional Oster",
        precio: 49300,
        cantidad: 1,
        img: "img/tienda/maquina-oster.jpg",
        descripcion: "",
    },
    {
        id: 9,
        nombre: "Peine de Oro",
        precio: 8020,
        cantidad: 1,
        img: "img/tienda/peine-oro.jpg",
        descripcion: "",
    },
]